apiVersion: apps/v1
kind: Replicaset
metadata:
  labels:
    app: nginx-app
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.0
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 128Mi